routes/web.php
<?php
namespace App\Http\Controllers;

use App\Models\CargaCategorias;
use App\Models\Certificado;
use App\Models\Curso;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});


Route::get('/', [WelcomeController::class, 'index']);
Route::get('login', [UserController::class, 'login'])->name('login');
Route::post('login', [UserController::class, 'login_post'])->name('login_post');
Route::get('logout', [UserController::class, 'logout'])->name('logout');
Route::get('verificarCertificado/{certificado}', [CertificadoController::class, 'verificarCertificado'])->name('verificarCertificado');

Route::group(['prefix' => 'administrador'], function () {
    Route::get('home', [WelcomeController::class, 'home'])->name('home');

    Route::get('categorias', [CategoriaCursoController::class, 'index'])->name('categorias');
    Route::post('saveCategoria', [CategoriaCursoController::class, 'store'])->name('saveCategoria');
    Route::get('deleteCategoria/{categoriaCurso}', [CategoriaCursoController::class, 'destroy'])->name('deleteCategoria');
    Route::post('updateCategoria', [CategoriaCursoController::class, 'update'])->name('updateCategoria');
    Route::get('cargaCategorias', [CargaCategoriasController::class, 'index'])->name('cargaCategorias');
    Route::post('cargaCategorias', [CargaCategoriasController::class, 'store'])->name('cargaCategorias_post');

    Route::get('cursos', [CursoController::class, 'index'])->name('cursos');
    Route::post('saveCurso', [CursoController::class, 'store'])->name('saveCurso');
    Route::get('deleteCurso/{curso?}',[CursoController::class, 'destroy'])->name('deleteCurso');
    Route::post('updateCurso', [CursoController::class, 'update'])->name('updateCurso');
    Route::get('cargaCursos', [CursoController::class, 'carga'])->name('cargaCurso');
    Route::post('cargaCursos', [CursoController::class, 'cargaStore'])->name('cargaCursos_post');
    Route::post('updateImagenCurso', [CursoController::class, 'updateImagenCurso'])->name('updateImagenCurso');

    Route::get('usuarios', [UserController::class, 'index'])->name('usuarios');
    Route::post('saveUsuario', [UserController::class, 'store'])->name('saveUsuario');
    Route::get('deleteUsuario/{usuario}', [UserController::class, 'destroy'])->name('deleteUsuario');
    Route::post('updateUsuario', [UserController::class, 'update'])->name('updateUsuario');
    Route::get('cargaUsuario', [UserController::class, 'carga'])->name('cargaUsuario');
    Route::post('cargaUsuario', [UserController::class, 'carga_post'])->name('cargaUsuario_post');

    Route::get('certificados', [CertificadoController::class, 'index'])->name('certificados');
    Route::get('deleteCertificado/{certificado}', [CertificadoController::class, 'destroy'])->name('deleteCertificado');
    Route::get('cargarCertificados', [CertificadoController::class, 'carga'])->name('cargarCertificados');
    Route::post('cargarCertificados', [CertificadoController::class, 'carga_post'])->name('cargarCertificados_post');
    Route::get('generarPdf/{certificado}', [CertificadoController::class, 'pdf'])->name('getPdf');
    Route::get('generarPng/{certificado}', [CertificadoController::class, 'png'])->name('getPng');
});

app/Models/Curso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Curso extends Model
{
    use HasFactory;
    protected $fillable = [
        'idCategoria', 'curso', 'descripcion', 'fecha_inicio', 'fecha_final', 'imagen', 'convocatoria'
    ];

    public function certificados()
    {
        return $this->hasMany(Certificado::class, 'idCurso', 'id');
    }
}

app/Http/Controllers/CursoController.php
<?php

namespace App\Http\Controllers;

use App\Models\{CategoriaCurso, Certificado, Curso, User};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Shuchkin\SimpleXLSX;

class CursoController extends Controller
{
    public function index()
    {
        $cursos = Curso::withCount('certificados')->get();
        $categorias = CategoriaCurso::all();

        $ruta = route('deleteCurso');

        return view('curso.list', compact('cursos', 'categorias', 'ruta'));
    }

    public function store( Request $request )
    {
        $file = $request->file('imagen');
        $curso = Curso::create([
            'idCategoria' => $request->idCategoria,
            'curso' => $request->curso,
            'descripcion' => $request->descripcion,
            'fecha_inicio' => $request->fecha_inicio,
            'fecha_final' => $request->fecha_fin,
            'imagen' => $this->upload_global($file, 'imagenes_cursos'),
            'convocatoria' => $request->convocatoria
        ]);

        return back()->with('success', 'Curso registrado con exito');
    }

    public function destroy(Curso $curso)
    {
        $certificados = Certificado::where('idCurso', $curso->id)->get();
        $count = Certificado::where('idCurso', $curso->id)->count();

        foreach ($certificados as $certificado) {
            DB::table('certificados')->delete($certificado->id);
        }

        $curso->delete();


        return back()->with('success', '1 Curso y '.$count.' Certificados eliminado con exito');
    }


    public function edit(Curso $curso)
    {
        return response()->json([
            'curso' => $curso
        ]);
    }

    public function update(Request $request)
    {
        $curso = Curso::updateOrCreate([
            'id' => $request->idCurso
        ],
        [
                'curso' => $request->curso,
                'descripcion' => $request->descripcion,
                'fecha_inicio' => $request->fecha_inicio,
                'fecha_final' => $request->fecha_fin,
                'convocatoria' => $request->convocatoria
        ]
        );

        return back()->with('success', 'Curso actualizado con exito');
    }

    public function carga()
    {
        return view('curso.carga');
    }

    public function cargaStore(Request $request)
    {
        $file = $request->file('cursos');
        $archivo = $this->upload_global($file, 'excels_cursos');

        if ($xlsx = SimpleXLSX::parse('uploads/excels_cursos/' . $archivo)) {
            $array = $xlsx->rows();
        } else {
            echo SimpleXLSX::parseError();
        }


        $i = 0;

        foreach ($array as $row) {
            $i++;
            if ($i > 1) {
                $curso =
                    Curso::create([
                        'idCategoria' => $row[1],
                        'curso' => $row[2],
                        'descripcion' => $row[3],
                        'fecha_inicio' => $row[4],
                        'fecha_final' => $row[5],
                        'convocatoria' => $row[6],
                    ]);
            }
        }


        //Excel::import(new CursosImport, 'uploads/excels_cursos/' . $archivo);

        return redirect()->route('cursos')->with('success', 'Carga realizada con exito');
    }

    public function updateImagenCurso( Request $request )
    {
        $curso = Curso::find($request->idCurso);
        $file = $request->file('imagen');
        $curso->imagen = $this->upload_global($file, 'imagenes_cursos');
        $curso->save();

        return back()->with('success', 'Actuaizacion de imagen realizada con exito');
    }


    function upload_global($file, $folder)
    {

        $file_type = $file->getClientOriginalExtension();
        $folder = $folder;
        $destinationPath = public_path() . '/uploads/' . $folder;
        $destinationPathThumb = public_path() . '/uploads/' . $folder . 'thumb';
        $filename = uniqid() . '_' . time() . '.' . $file->getClientOriginalExtension();
        $url = '/uploads/' . $folder . '/' . $filename;

        if ($file->move($destinationPath . '/', $filename)) {
            return $filename;
        }
    }


}

resources/views/curso/carga.blade.php
@extends('layouts.app')

@section('contenido')
        <h4 class="tx-gray-800 mg-b-5">Cargar Cursos</h4>
    <div class="br-pagebody">
        <div class="br-section-wrapper">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block mt-20" style="margin-top: 20px">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong> {{ $message }} </strong>
                </div>
            @endif
                <form action="{{route('cargaCursos_post')}}" method="POST" accept-charset="UTF-8"
                    enctype="multipart/form-data">
                    @csrf
            <div class="form-group">
                <label for="">Cargar Archivo</label>
                <input type="file" name="cursos" class="form-control">
            </div>

            <input type="submit" value="Cargar" class="form-control btn btn-success">
            </form>
        </div>
    </div>

@endsection

resources/views/curso/list.blade.php
@extends('layouts.app')

@section('contenido')
    <h4 class="tx-gray-800 mg-b-5">Listado de Cursos</h4>
    <button class="btn btn-success pull-right" data-toggle="modal" data-target="#modaldemo1"> <i
            class="fa fa-plus-circle"></i> Agregar Curso</button>
    <div class="br-pagebody">
        <div class="br-section-wrapper">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block mt-20" style="margin-top: 20px">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong> {{ $message }} </strong>
                </div>
            @endif
            <div class="table-wrapper">
                <table id="datatable1" style="width: 100%" class="table display responsive nowrap">
                    <thead>
                        <tr width="100%">
                            <th width="33%">Id</th>
                            <th width="33%">Curso</th>
                            <th width="33%">Certificados</th>
                            <th width="33%">Convocatoria</th>
                            <th width="33%">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($cursos as $curso)
                            <tr>
                                <td>{{ $curso->id }}</td>
                                <td>{{ $curso->curso }}</td>
                                <td class="text-center">{{ $curso->certificados_count }}</td>
                                <td>{{ $curso->convocatoria }}</td>
                                <td>
                                    <a href="#" onclick="editarCurso({{ $curso->id }})"><i
                                            class="fa fa-edit text-primary"></i></a>
                                    <a href="#" onclick="eliminar({{ $curso->certificados_count }}, {{ $curso->id }}, '{{$ruta}}')"><i
                                            class="fa fa-trash text-danger"></i></a>
                                    <i class="fa fa-image text-warning" onclick="cargarImagen({{ $curso->id }})"></i>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div><!-- table-wrapper -->
        </div>
    </div>




    <!-- BASIC MODAL -->
    <div id="modaldemo1" class="modal fade">
        <div class="modal-dialog modal-lg" style="width: 60% !important" role="document">
            <div class="modal-content bd-0 tx-14">
                <div class="modal-header pd-y-20 pd-x-25">
                    <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">AGREGAR CURSO</h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body pd-25">
                    <form action="{{ route('saveCurso') }}" method="POST" accept-charset="UTF-8"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="">Categoria</label>
                            <select name="idCategoria" required class="form-control" id="">
                                <option value="">SELECCIONE</option>
                                @foreach ($categorias as $categoria)
                                    <option value="{{ $categoria->id }}">{{ $categoria->categoria }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="">Curso</label>
                            <input type="text" required name="curso" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="">Descripcion</label>
                            <textarea name="descripcion" required id="" class="form-control" rows="10"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="">Fecha Inicio</label>
                            <input type="date" required name="fecha_inicio" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="">Fecha Fin</label>
                            <input type="date" required name="fecha_fin" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="">Convocatoria</label>
                            <input type="text" required name="convocatoria" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="">Imagen</label>
                            <input type="file" required name="imagen" class="form-control">
                        </div>

                </div>
                <div class="modal-footer">
                    <button type="submit"
                        class="btn btn-primary tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium">Guardar
                        Cambios</button>
                    <button type="button" class="btn btn-secondary tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium"
                        data-dismiss="modal">Cerrar</button>
                    </form>
                </div>
            </div>
        </div><!-- modal-dialog -->
    </div><!-- modal -->



    <!-- BASIC MODAL -->
    <div id="modaldemo2" class="modal fade">
        <div class="modal-dialog modal-lg" style="width: 60% !important" role="document">
            <div class="modal-content bd-0 tx-14">
                <div class="modal-header pd-y-20 pd-x-25">
                    <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">EDITAR CURSO</h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body pd-25">
                    <form action="{{ route('updateCurso') }}" method="POST" accept-charset="UTF-8"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="">Categoria</label>
                            <select name="idCategoria" required class="form-control" id="categoria">
                                <option value="">SELECCIONE</option>
                                @foreach ($categorias as $categoria)
                                    <option value="{{ $categoria->id }}">{{ $categoria->categoria }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="">Curso</label>
                            <input type="text" name="curso" id="curso" class="form-control">
                            <input type="hidden" name="idCurso" id="idCurso" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="">Descripcion</label>
                            <textarea name="descripcion" id="descripcion" class="form-control" rows="10"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="">Fecha Inicio</label>
                            <input type="date" name="fecha_inicio" id="fecha_inicio" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="">Fecha Fin</label>
                            <input type="date" name="fecha_fin" id="fecha_final" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="">Convocatoria</label>
                            <input type="text" name="convocatoria" id="convocatoria" class="form-control">
                        </div>


                </div>
                <div class="modal-footer">
                    <button type="submit"
                        class="btn btn-primary tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium">Guardar
                        Cambios</button>
                    <button type="button" class="btn btn-secondary tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium"
                        data-dismiss="modal">Cerrar</button>
                    </form>
                </div>
            </div>
        </div><!-- modal-dialog -->
    </div><!-- modal -->



    <div id="modaldemo3" class="modal fade">
        <div class="modal-dialog modal-lg" style="width: 60% !important" role="document">
            <div class="modal-content bd-0 tx-14">
                <div class="modal-header pd-y-20 pd-x-25">
                    <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">CARGAR IMAGEN DEL CURSO</h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body pd-25">
                    <form action="{{ route('updateImagenCurso') }}" method="POST" accept-charset="UTF-8"
                        enctype="multipart/form-data">
                        @csrf

                        <div class="form-group">
                            <label for="">Imagen</label>
                            <input type="file" name="imagen" class="form-control">
                            <input type="hidden" name="idCurso" id="idCursoImagen">
                        </div>

                </div>
                <div class="modal-footer">
                    <button type="submit"
                        class="btn btn-primary tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium">Guardar
                        Cambios</button>
                    <button type="button" class="btn btn-secondary tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium"
                        data-dismiss="modal">Cerrar</button>
                    </form>
                </div>
            </div>
        </div><!-- modal-dialog -->
    </div><!-- modal -->
@endsection


@section('scripts')
    <script>
        function editarCategoria(idCategoria) {
            axios.get('/api/categoria/' + idCategoria).then((response) => {
                $("#categoria").val(response.data.categoria.categoria)
                $("#idCategoria").val(response.data.categoria.id)
                $("#modal2").modal('show')
            })
        }

        function editarCurso(idCurso) {
            axios.get('/api/curso/' + idCurso).then((response) => {
                $("#curso").val(response.data.curso.curso)
                $("#descripcion").val(response.data.curso.descripcion)
                console.log(response.data.curso.idCategoria)
                $("#categoria option[value=" + response.data.curso.idCategoria + "]").attr("selected", true)
                $("#fecha_inicio").val(response.data.curso.fecha_inicio)
                $("#fecha_final").val(response.data.curso.fecha_final)
                $("#convocatoria").val(response.data.curso.convocatoria)
                $("#idCurso").val(response.data.curso.id)
                $("#modaldemo2").modal('show')
            })
        }

        function cargarImagen(idCurso) {
            $("#modaldemo3").modal('show')
            $("#idCursoImagen").val(idCurso)
        }

        function eliminar(count, idCurso, ruta) {
            Swal.fire({
                title: 'Deseas realmente eliminar, el curso? este contiene un total de '+count+' certificados, si lo eliminas, eliminas con el sus certificados.',
                showDenyButton: true,
                showCancelButton: true,
                confirmButtonText: 'Eliminar',
                denyButtonText: `No Eliminar`,
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = ruta+"/"+idCurso;
                } else if (result.isDenied) {

                }
            })
        }


        $('#datatable1').DataTable({
            responsive: true,
            language: {
                searchPlaceholder: 'Buscar',
                sSearch: '',
                lengthMenu: '_MENU_ Reistro por Pagina',
                paginate: {
                    first: "Primera",
                    previous: "Anterior",
                    next: "Siguiente",
                    last: "Ultima"
                },
                info: "Mostrando _START_ de _END_ en _TOTAL_ registros",
            }
        });
    </script>
@endsection